# Generated by Django 2.2.3 on 2019-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fi',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
