# Generated by Django 2.2.3 on 2019-08-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0003_auto_20190820_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
