# Generated by Django 2.2.4 on 2019-08-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0005_blog1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blog1',
        ),
    ]
